### ISSUE TITLE
AttributeError: Connect instance has no attribute 'host'

### ISSUE THREAD

**Issue by areben** [kootenpv/yagmail#1]
Running your simple test example..
  
File "/usr/local/lib/python2.7/dist-packages/yagmail/__init__.py", line 31, in __init__
    self.login(password)
  File "/usr/local/lib/python2.7/dist-packages/yagmail/__init__.py", line 65, in login
    self.smtp = smtplib.SMTP(self.host, self.port) 
AttributeError: Connect instance has no attribute 'host'
shutting...
Exception AttributeError: "Connect instance has no attribute 'smtp'" in <bound method Connect.__del__ of <yagmail.Connect instance at 0x7fad75949998>> ignored

**Comment by kootenpv** [comment]
Hi, thanks for filing the issue! It should be resolved in the new version. (pip install -U yagmail).

**Comment by kootenpv** [comment]
Please let me know if it has been resolved.
