### ISSUE TITLE
Image compression

### ISSUE THREAD

**Issue by vikas-parashar** [kootenpv/yagmail#10]
I am working on image compression for attachments. Should I try lossy or losslesss compresion?

**Comment by kootenpv** [comment]
My main goal was to resize images for nicely/easily displaying inline images. However, now that everything is in HTML, perhaps setting `width` and `height` on the `<img>` would also work. In that light, do you still think it could be useful to compress the images?

**Comment by vikas-parashar** [comment]
Yeah, setting `width` and `height` would work. I don't think we need compression.
