### ISSUE TITLE
UnicodeEncodeError when unicode symbols in contents body

### ISSUE THREAD

**Issue by NesCafe62** [kootenpv/yagmail#101]
When I tried to send email with utf-8 symbols in contents it says:
UnicodeEncodeError: 'ascii' codec can't encode charachters in position 0-4: ordinal not in range(128)

Kinda filesystem can work with only ascii strings. I fixed this by adding a check in yagmail/sender.py [line 402]:
`is_unicode = False
try:
    q = content_string.decode('ascii')
except:
    is_unicode = True
if (not is_unicode) and os.path.isfile(content_string) and not is_raw:`

**Comment by qria** [comment]
I also had a similar issue and solved it via setting the environment variables to allow non-ascii strings in filename like this:

```bash
export LANG='en_US.UTF-8'
export LC_ALL='en_US.UTF-8'
```

c.f.) https://stackoverflow.com/a/10396375/1794230

**Comment by CraiHe** [comment]
I also meet the same issue and solved it via adding an encode in yagmail/message.py [line 126]:
`if not is_raw and os.path.isfile(content_string.encode("utf-8")):`

**Comment by kootenpv** [comment]
I think we can close this as @qria qria seems to have a reasonable answer here.
