### ISSUE TITLE
[Errno 101] Network is unreachable

### ISSUE THREAD

**Issue by CommYutzy** [kootenpv/yagmail#104]
Ubuntu 16.04
Python 2.7.12

Getting the following error when I try to send an email. Machine has internet connectivity and the firewall is configured to allow all outbound traffic. The gmail account is set to allow insecure apps. Password is properly stored in keyring.

>>> yagmail.SMTP('abc@gmail.com').send('def@gmail.com', 'Test', 'This is a test')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python2.7/site-packages/yagmail/sender.py", line 78, in __init__
    self.login(password)
  File "/home/user/.local/lib/python2.7/site-packages/yagmail/sender.py", line 193, in login
    self.smtp = self.connection(self.host, self.port, **self.kwargs)
  File "/usr/lib/python2.7/smtplib.py", line 801, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout)
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 806, in _get_socket
    new_socket = socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
socket.error: [Errno 101] Network is unreachable

**Comment by kootenpv** [comment]
That should just simply work - it still is probably a network problem.... see also: https://stackoverflow.com/questions/14949492/errno-101-network-is-unreachable-when-trying-to-send-email-using-django

**Comment by CommYutzy** [comment]
So looking at that it appears the user who reported the issue is using third party hosting. My box is sitting at my house, connected directly to the 2nd port of my modem receiving it's own IP address. Only firewall is iptables, which as mentioned allows all outbound. Is there possibly an inbound that needs allowed?

**Comment by CommYutzy** [comment]
Ok got it fixed, I realized I wasn't connection tracking any inbounds. Added the following and it worked, this may actually fix my Steam networking issue as well...

`sudo iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT`
