### ISSUE TITLE
FileNotFound?

### ISSUE THREAD

**Issue by Kgraves114** [kootenpv/yagmail#108]
Hello, I am hoping I can get some help with this issue. i am running this code in an ipython notebook.
Here is the program:
import yagmail

with open("email_template.txt") as f:
    email_template = f.read()

template_data = [
    ("test1@gmail.com", "G. Hub", "GitHub"),
    ("test2@gmail.com", "L. Inkedin", "LinkedIn"),
    ("test3@gmail.com", "R. Editor", "Reddit")
]

yag = yagmail.SMTP()
for to_email, name, social_network in template_data:
    txt = email_template.format(name=name, social_network=social_network)
    # contents, attachments, to, cc, bcc -- all can be a list (plural) or a string (singular)
    #contents = [txt, 'brand1.png', 'logo2.png']
    yag.send(to_email, "Hi!", contents)

And here is my error:
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-7-a64ee4d1edf4> in <module>()
     10 ]
     11 
---> 12 yag = yagmail.SMTP()
     13 for to_email, name, social_network in template_data:
     14     txt = email_template.format(name=name, social_network=social_network)

~\AppData\Roaming\Python\Python36\site-packages\yagmail\sender.py in __init__(self, user, password, host, port, smtp_starttls, smtp_ssl, smtp_set_debuglevel, smtp_skip_login, encoding, oauth2_file, soft_email_validation, **kwargs)
     59             user = ''
     60         elif user is None:
---> 61             user = self._find_user_home_path()
     62         self.user, self.useralias = self._make_addr_alias_user(user)
     63         self.soft_email_validation = soft_email_validation

~\AppData\Roaming\Python\Python36\site-packages\yagmail\sender.py in _find_user_home_path()
    344     @staticmethod
    345     def _find_user_home_path():
--> 346         with open(os.path.expanduser("~/.yagmail")) as f:
    347             return f.read().strip()
    348 

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\kgraves/.yagmail'

This is my first time working with yagmail so I am unsure where I am going wrong.

**Comment by kootenpv** [comment]
You have to provide login information. I encourage you to read the Readme
:) good luck!
