### ISSUE TITLE
Web Login Required

### ISSUE THREAD

**Issue by Hu1-Li** [kootenpv/yagmail#111]
Hi, I'm using the python smtp library to send email using google account, but got this
`5.7.9 Please log in with your web browser and then try again. Learn more at\n5.7.9  https://support.google.com/mail/?p=WebLoginRequired`

So will i get the same problem after using `yagmail`?

**Comment by Lvl4Sword** [comment]
In https://github.com/kootenpv/yagmail#errors there's:
- Click to enable the email for being used externally https://www.google.com/settings/security/lesssecureapps

**Comment by kootenpv** [comment]
Did that solve it @Hu1-Li ?
