### ISSUE TITLE
Change email font

### ISSUE THREAD

**Issue by lukeweller** [kootenpv/yagmail#112]
Is there currently any way to change the font for the email contents?

I know Gmail does support a few different fonts for content (Sans Serif, Fixed Width, etc.), but I am unable to find any documentation on font for yagmail.

Yagmail has worked excellently for me, thank you for creating it!

**Comment by lukeweller** [comment]
To be more specific, I'm looking for a way to change the font to fixed width.

**Comment by kootenpv** [comment]
You could add the text in <code> tags, that's probably easiest. Would that
work for you? Otherwise you could set the font style on the highest level
element.

**Comment by lukeweller** [comment]
The <code> tag does exactly what I need.

Thank you
