### ISSUE TITLE
send yagmail with html content, and receive mail get some blank line 

### ISSUE THREAD

**Issue by shenghaomail** [kootenpv/yagmail#124]
here is my script to send mail 
`html = """\`
`   <table width="500" border="2" bordercolor="red" cellspacing="2">`
`  <tr>`
`    <td><strong>action</strong></td>`
`    <td><strong>total</strong></td>`
`    <td><strong>action</strong></td>`
`    <td><strong>pre</strong></td>`
`    <td><strong>unsure</strong></td>`
`  </tr>`
`  <tr>`
`    <td>node</a></td>`
`    <td>1</td>`
`    <td>2</td>`
`    <td>3</td>`
`    <td>4</td>`
`    <td>5</td>`
`  </tr>`
`</table>`
`            """`
`to = 'abc@abc.com'`
`subject = 'This is obviously the subject'`
`body = 'This is obviously the body'`
`yag = SMTP_SSL(user = yag_user, password = yag_password, host = yag_host,port = yag_port)`
`yag.send(to=to, subject=subject, contents=[body, html])`

and there is some blank line between `body` and `html `

**Comment by kootenpv** [comment]
There's a separation of content between each element in contents.

If you want you could just do `, contents=body + html`, that should avoid the blank line?

**Comment by shenghaomail** [comment]
thank you for reply!
Test the following three commands, and the execution results contain blank lines.
`yag.send(to=to, subject=subject, contents=[body, html])`
`yag.send(to=to, subject=subject, contents=body + html)`
`yag.send(to=to, subject=subject, contents=html)`

<img width="587" alt="qq20180908-091612 2x" src="https://user-images.githubusercontent.com/26991742/45248739-defd6b00-b347-11e8-90a6-1a2e155757c2.png">

**Comment by kootenpv** [comment]
Newlines are converted to <br> as a matter of convenience.

You can avoid this using `html = html.replace("\n", "")`

**Comment by shenghaomail** [comment]
Thank you!
blank lines is gone

**Comment by kootenpv** [comment]
Note that there is also a possibility now to add `yag.send(contents="test\ntest", newline_to_break=False)`, that could also help.
