### ISSUE TITLE
no module named error

### ISSUE THREAD

**Issue by martinberoiz** [kootenpv/yagmail#13]
Hello,

Right after installing yagmail with pip install I get this error as soon as I import the module:

> > > import yagmail
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/local/lib/python2.7/site-packages/yagmail/**init**.py", line 6, in <module>
> > >     from .yagmail import SMTP
> > >   File "/usr/local/lib/python2.7/site-packages/yagmail/yagmail.py", line 16, in <module>
> > >     from .validate import validate_email_with_regex
> > >   File "/usr/local/lib/python2.7/site-packages/yagmail/validate.py", line 31, in <module>
> > >     from yagmail.error import YagInvalidEmailAddress
> > > ImportError: No module named error

What could this be?

**Comment by kootenpv** [comment]
Could you try rerunning it with `pip install -U yagmail`? I thought this should be solved by now by using `from __future__ import absolute_import` at the top of the script.

**Comment by martinberoiz** [comment]
Oh, ok. It must be just me then. I tried with -U option but didn't work either.

**Comment by kootenpv** [comment]
Actually, thanks for raising an issue! It apparently wasn't working for Python 2.7

I guess somehow the test didn't catch it.

See also the following issue:

https://github.com/kootenpv/yagmail/commit/4a434976fd23d98ca69772d632ccaa5c535d7bf8

**Comment by wingnut2626** [comment]
Hello, I have installed yagmail via 

sudo pip3 install yagmail

on my system.  I am getting an ImportError with no module of that name.  Any ideas?

**Comment by kootenpv** [comment]
@wingnut2626  Try to update to a newer version perhaps: `sudo pip3 install -U yagmail`

**Comment by guigashm** [comment]
Hello,

I had a similar issue, solved by using `sudo`.

I used:
`sudo pip install yagmail `

In the yagmail GIT page, probably the instructions should have:

`sudo pip install yagmail `
`sudo pip3 install yagmail `

**Comment by kootenpv** [comment]
@guigashm Strange, I'm able to install without sudo on a new system. I'm out of ideas. But I took your advice into the README at the errors section. Thanks for posting.

**Comment by Lvl4Sword** [comment]
I would suggest not using sudo to pip install anything. Do you have another file called error.py?

Doing the following works on Debian 9:
- virtualenv -p python3 yagmail_venv
- ~/yagmail_venv/bin/pip install yagmail
- python3
- import yagmail

**Comment by kootenpv** [comment]
I think this is not an issue anymore? Feel free to reopen.

**Comment by jerzybrzoska** [comment]
Yeah, it still happens: 
>ModuleNotFoundError: No module named 'yagmail' 

Didn't happen last year. though. I installed it via `pip3 install yagmail`. `pip3 install -U yagmail` does not help at all.

**Comment by kootenpv** [comment]
> Yeah, it started to happen again:
> 
> > ModuleNotFoundError: No module named 'yagmail'
> 
> Didn't happen last year. though. I installed it via `pip3 install yagmail`. `pip3 install -U yagmail` does not help at all.

Did you try `python3` afterwards, i.e. the same version as `pip3`
