### ISSUE TITLE
Body always empty when used as CLI

### ISSUE THREAD

**Issue by mpolidori** [kootenpv/yagmail#132]
I'm unable to get the `-contents` flag to work from the CL. I don't receive an error. The command runs as if it were successful, but the body is always blank. Not sure where to begin problem solving here. Also, when I use it in a project everything works as intended. The issue is only present when I'm using the CLI.

I'm using Arch Linux, and I've tried with multiple Python versions. Any ideas?

**Comment by kootenpv** [comment]
Thanks for taking the time to post.

Did you try with either `--contents "hi this is the contents"` or `-c "hi this is the contents"`, the other way it should work could be `--contents hi this is the contents`?

**Comment by kootenpv** [comment]
Thanks a lot btw, and I'm really sorry for being so slow. This was introduced when I also wanted to allow piping data to yagmail as content. Now both work, i.e.:

    echo "hi" | yagmail -u you -oauth2 oauth2.json 
    yagmail -u you -oauth2 oauth2.json -c hi
