### ISSUE TITLE
Using Yagmail with a self-hosted SMTP server, any gotchas?

### ISSUE THREAD

**Issue by SkullTech** [kootenpv/yagmail#133]
I'm planning to use yagmail with not just Gmail, but any and all SMTP servers. I've looked through the code and I've seen that you made the library general enough — but still I wanted to ask if there's any Gmail-specific things you've implemented here that I should keep in mind?

**Comment by kootenpv** [comment]
@SkullTech I think yagmail succeeded at not burning any bridges for other providers (even though preferring gmail). Please let me know if there are any issues.
For local SMTP server you might need to use `smtp_skip_login=True`.

**Comment by SkullTech** [comment]
@kootenpv There's a large thing you overlooked, you aren't taking the _sender address_ and _sender name_ variables from the user, not even as an optional argument. You're deducing them from the `user` argument passed to the `SMTP` constructor, but for other SMTP servers this won't be enough.

**Comment by kootenpv** [comment]
@SkullTech That was a deliberate choice to prevent spoofing - but I see how this can be annoying.

**Comment by tiny-dancer** [comment]
@SkullTech looking at using yagmail in a similar fashion - any updates on the implementation?

**Comment by tiny-dancer** [comment]
likely related to original comment above: https://github.com/kootenpv/yagmail/issues/115

**Comment by SkullTech** [comment]
@tiny-dancer I ended up implementing this on my own, in a similar but but open-ended way. You can find the project here — [drymail](https://github.com/SkullTech/drymail).

**Comment by kootenpv** [comment]
I'm fine with that. Feel free to use drymail if you want to set your own custom headers. If someone can provide a good reason for me to change my mind, feel free to try. Closing for now.

**Comment by saerdnaer** [comment]
Here is an example:

```python
import yagmail
from getpass import getpass

receiver = "receiver@domain.tld"
body = """Hello there from Yagmail

--
Your friendly python script"""
    
password = getpass("Type your password and press enter: ")

yag = yagmail.SMTP("you@yourdomain.tld", password, host="mail.yourdomain.de", port=587, smtp_starttls=True, smtp_ssl=False)
yag.send(
    to=receiver,
    subject="Yagmail test with attachment",
    contents=body, 
    #attachments=filename,
)
```

I could not find one in the docs, so I looked the parameters up in the source code https://github.com/kootenpv/yagmail/blob/f3612b3866c1120e1d3acd760c90f5694b5e39a3/yagmail/sender.py#L22-L37
