### ISSUE TITLE
"smtplib.SMTPServerDisconnected: Connection unexpectedly closed" after 80+ emails

### ISSUE THREAD

**Issue by Rmckinstry** [kootenpv/yagmail#142]
I am using this to send a weekly report to all vendors working with our company to remind them of all purchase orders. The send list typically is 150+. I get this full error around 80-96 emails in).

**Comment by berkowitze** [comment]
Also getting this error. Using with or login/close doesn't solve the problem.

**Comment by FilipGrebowski** [comment]
@Rmckinstry Did you manage to find a solution to this? It happened to me also.

**Comment by Rmckinstry** [comment]
@FilipGrebowski the only way I got around it was hard coding a cool down between each email being sent. It’s been a while but I believe it was a second or so. If that doesn’t work try hard coding a 1-3 min cool down after 60 or so emails have been sent

**Comment by twomed** [comment]
I was having the same issue with only being able to get 80-90 emails out until I added a sleep(1.5) which allowed me to get the whole batch out

**Comment by kootenpv** [comment]
Probably to do with gmail rate limiting
