### ISSUE TITLE
"noname" attached filenames

### ISSUE THREAD

**Issue by DaWy** [kootenpv/yagmail#159]
When attaching filenames, gmail is showing those files as **noname** filename. It's happening to me today, without upgrading anything. So I don't know it's gmail related or its yagmail related. The files attached are all PDF files, and all sended files has this noname problem. 

Throwing what I'm doing to attaching files and send mails.

```
line_invoice_path = PATH_TO_PDF_FILE
contents = []
contents.append(line_invoice_path)
yag.send(mail_to, subject, contents)
```

I've been using this script about more than 1 year without problems. Just today I realised attached filenames are wrong...

**Comment by kootenpv** [comment]
Thanks for reporting this! I'll keep an eye out, but I think I am currently not sending attachments.

**Comment by larsbijl** [comment]
I'm seeing the same issue

**Comment by fvallebas** [comment]
Same issue here

**Comment by DaWy** [comment]
Any update or hint on this? @kootenpv

**Comment by djnugent** [comment]
Still an issue

**Comment by djnugent** [comment]
Solution for people who dont want to wait for a fix
```python
import smtplib
from os.path import basename
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
import mimetypes
from email import encoders
import json


class Email:

    def __init__(self, email_auth):
        data = json.load(open(email_auth, "r"))
        self.sender_addr = data["email"]
        self.sender_pass = data["password"]

    def send(self, send_to, subject, body, attachments=[], reply_to=None):
        msg = MIMEMultipart()
        msg['From'] = self.sender_addr
        msg['To'] = send_to
        msg['Subject'] = subject

        msg.attach(MIMEText(body))

        if reply_to is not None:
            msg.add_header('reply-to', reply_to)

        for a in attachments:
            with open(a, "rb") as fil:
                content_type = mimetypes.guess_type(a)[0].split("/")
                part = MIMEBase(content_type[0], content_type[1])
                part.set_payload(fil.read())
                encoders.encode_base64(part)
                part.add_header('Content-Disposition', "attachment; filename= %s" % basename(a))
                msg.attach(part)

        server = smtplib.SMTP_SSL('smtp.gmail.com', 465)
        server.ehlo()
        server.login(self.sender_addr, self.sender_pass)
        server.sendmail(self.sender_addr, send_to, msg.as_string())
        server.close()
```

**Comment by DaWy** [comment]
Hi,

Sorry, i forgot about this issue. I'm still dealing with this problem everymonth (as we use an script for sending pdf bills everymonth with yagmail)

OS: Debian 10, running on docker container
Python Version: 2.7.16
Docker Engine Version: 19.03.11 

I'm throwing here all the steps i'm following to create the mails with the noname file attachments. 

```
import yagmail, os

# line_list is getting a list of lines from our company internal api

for line in line_list:
    line_invoice_path = "/path/to/invoices/%s.pdf"  % line.number
    # The invoice file name is something like: 666777888.pdf and its a regular PDF file extracted from our provider website.
    if os.path.exists(line_invoice_path):
        contents = []
        contents.append(line_invoice_path)
        html = ""
        subject = '[Factura Movistar][%s][%s]' % (line.invoice_date, line.number)
        contents.append(html)
        yag.send(line.mail, subject, contents)
```

That's basically what i'm doing for sending invoices. PDF invoice path is correct as file is getting attached correctly. Could be something with encryption? or mail mimetype? Or maybe that PDF files are encrypted? I don't know. 

What I could try is to run this on Python 3.7. But that would require me to upgrade whole app and its a lot of time.

**Comment by kootenpv** [comment]
Did you try updating yagmail by any chance? That's a small step at least...

**Comment by DaWy** [comment]
> My sympathies for our situation... I'll look more into it when i have the chance.
> 
> Did you try updating yagmail by any chance? That's a small step at least...

Well, after more testing I decided to update my whole app to support latest python version (3.9) and now, with the same exact code for this part the attached files names are showing correctly in the received mail.

So it's solved by updating Python version... 

If anyone is facing this issue then you have to upgrade to Python 3.9 and use last version of this module. 

Thanks for the support @kootenpv !
