### ISSUE TITLE
always prompts for keyring password on Ubuntu

### ISSUE THREAD

**Issue by loraxman** [kootenpv/yagmail#16]
After registering the user and email, it prompts everytime for the encrypted keyring password.
yag = yagmail.SMTP()
Please enter password for encrypted keyring: 

Works fine on Mac Os

**Comment by kootenpv** [comment]
I'll test this on a Ubuntu VM and let you know.

**Comment by kootenpv** [comment]
Using Python 3.4 and Ubuntu, I can not reproduce. What could be the thing is that perhaps you are not consistent with what you've saved? A username (e.g. kootenpv) would be stored differently as an emailaddress (e.g. kootenpv@gmail.com). 

However, if you've saved it in one style, it does not work for the other. Could that be the case?

**Comment by murtraja** [comment]
i too have this issue!
steps to reproduce
1. go to pythonanywhere.com
2. create an account
3. open bash
4. pip install --user keyrings.alt yagmail
5. python
6. import yagmail
7. yagmail.register("user","pass")
8. set keyring password here
9. now create .yagmail file and test with SMTP
10. it asks for keyring password EVERY time

**Comment by kootenpv** [comment]
`.yagmail` file should be in $HOME directory. Is it?

**Comment by kootenpv** [comment]
Let me know if you'd like me to add a "do you want to save a .yagmail file?" after the question whether or not to save in keyring.

**Comment by murtraja** [comment]
![yagmail_prob](https://cloud.githubusercontent.com/assets/7806954/13011026/d894eee8-d1ca-11e5-98ca-e3cf0912a1b1.PNG)

do i need to give a terminating end line  in the yagfile?

**Comment by kootenpv** [comment]
No need for it. Make sure the username of gmail should be in `.yagmail`, not the username on the PC.

**Comment by kootenpv** [comment]
You can actually test by using "yagmail" command on the command line to see if it worked (if it works, no prompt, and it should send an email to yourself without subject and without contents)

**Comment by murtraja** [comment]
![yagmail_prob_yagmail_command](https://cloud.githubusercontent.com/assets/7806954/13013378/4253becc-d1d5-11e5-8eec-7375d102cc2d.PNG)

**Comment by murtraja** [comment]
it turns out that the username of PC and gmail are the same!

**Comment by kootenpv** [comment]
So did it work in the end?

**Comment by GeorgHo** [comment]
Hello,
I have the same problem on a Debian system (Raspberry Pi).
He always asks for a Keyring Key to decrypt the Keyring file where the password is stored in.
I have installed the keyrings.alt backend.
I have not found a solution to store this password, so that it is dragged automatically.

**Comment by kootenpv** [comment]
@GeorgHo Perhaps it could work to just put the password in the script in that occasion then?

**Comment by GeorgHo** [comment]
Hi kootenpv,
I solved the problem by entered the login data in the script.
Now everything works fine!

**Comment by kootenpv** [comment]
@GeorgHo Great to hear, good luck!

**Comment by murtraja** [comment]
@GeorgHo even i did the same to make it work, but it defeats the purpose of securing your username and password. anyone who can view your script can see your username => you can't share your script!

**Comment by kootenpv** [comment]
@murtraja I'm thinking OAuth2 is the only way to solve running the script in an automated way without having to use keyring or password in script, and without compromising security. What do you think?

**Comment by murtraja** [comment]
The only reason I am using yagmail is because it DOES NOT use Oauth2.
Reason being it screws up my automation email sending sometimes.!. That
said, if you have already decided, try not to replace, make it like add on.
Thanks

**Comment by Jokerbullot** [comment]
I do have the same issue on Debian (Raspberry Pi).
I do have a .yagmail file in my home with just my gmail login (without @gmail.com)

when running python3 test_mail.py it asks me the keyring pwd and then succesfully send the email.

I tried adding or removing my login in the yagmail.SMTP() call but it does not change anything.

Any1 found a way to solve this ?

Tyvm all.

**Comment by kootenpv** [comment]
Oauth2 support has been added as of https://github.com/kootenpv/yagmail/commit/22cb687adc67fd9b16f870e5e658a3fa77ca67ac

This should be the way forward.
