### ISSUE TITLE
raw format not working, plus need a clarification

### ISSUE THREAD

**Issue by cmdlinebeep** [kootenpv/yagmail#161]
Thanks for the great project!

My main issue is that extra line breaks seem to be added to my emails.  For example, a snippet from my html content is: 
`Hi there,</p>`
which is being replaced (when I examine the raw email sent) with:
`Hi there,</p><br>`
And I am using:
`yag.send(to=to, subject=subject, contents=[body, yagmail.raw(html)])`
Which runs without errors.  Am I doing this correct?  Why is it modifying my HTML?

Secondly, if you could help me understand the difference between when to use body versus html.  In many email clients I've used, they automatically take an HTML email and, to display properly on older email clients, also create a plain-text version of the text and links.  

Most mail clients then attach both versions, with the second one the one the client email app should try to display first (typically HTML version).  The versions are separated like:
```
Content-Type: text/plain; charset="UTF-8"
Content-Transfer-Encoding: quoted-printable
```
(and another one with content-type text/html)

From what I observe, Yagmail is also having these two content types, but the plain-text version is just the exact same HTML content **PLUS** the body portion is wrapped in `<div></div>` tags.

How do I do what I'm trying to do, where the HTML content is provided, and for mail clients that can only open plaintext, just the simplified text from the HTML is printed instead?  I am probably doing something wrong, like maybe I don't want to use `body `at all?  I'm not finding this documented but perhaps I missed it.

p.s. Even if I drop the `body` content and just send yagmail.raw(html), I am still getting loads of whitespace added to the email.

Thanks for your help!

**Comment by cmdlinebeep** [comment]
OK, I found this tip in another filed issue and that resolved it for me.

`html = html.replace("\n", "")`

However, would still appreciate any guidance on the second half of my above question!  Basically, how can I ensure that my email shows up readable on email clients that don't support HTML (as rare as those are)?

**Comment by kootenpv** [comment]
Should be solved with the new code

**Comment by NikolayVoronkov** [comment]
0.14.245 still not working

**Comment by joaomcarlos** [comment]
0.15.293 still not working
