### ISSUE TITLE
How can I send email in plain text?

### ISSUE THREAD

**Issue by aktywnitu** [kootenpv/yagmail#166]
Hi,

I am trying to send email with plain text, but I always receive email with <br> tags.
`yag.send(data['email'], data['subject'], data['contents'])`

**Comment by ajgringo619** [comment]
If this is not a feature, please add it if possible!!! I created a gmail account exclusively for sending updates from my PC to my phone and personal email, and the formatting looks horrible in HTML.

**Comment by ajgringo619** [comment]
I've found that my test emails are being sent as html/text; at least I can use my email program (Evolution) to select the format I want to see. The docs here mention a raw setting for forcing emails in text only, but I can't get it to work.

**Comment by kootenpv** [comment]
Does the following not work?

    import yagmail
    yag = yagmail.SMTP("username", "password")
    yag.send(contents=yagmail.raw("hi"))

**Comment by ajgringo619** [comment]
I can switch the view to plain text, but it's coming in as both html and text. I was hoping to send text-only emails, mainly to my phone (as SMS), but also to my PC.

**Comment by kootenpv** [comment]
I guess for simple emails you can then simply use smtplib.

**Comment by ajgringo619** [comment]
OK, no big deal. Using the .raw method works great on my phone; the only anomaly is that the last 2 characters get cut off the body of the message (seriously doubt that's on your end). Thanks for your help!

**Comment by kootenpv** [comment]
Thanks
