### ISSUE TITLE
How to specify 'raw'?

### ISSUE THREAD

**Issue by orotau** [kootenpv/yagmail#17]
Hi there
Thanks for the package, working well.
I am using it with a textarea on a cherrypy site as follows.
```python
def thankyou(self, feedback):
    import yagmail
    yag = yagmail.SMTP('greenbay.graham')
    yag.send(subject = 'subject', contents = feedback)
```
The email is being sent but I get this error in the error log 
```'shell
[yagmail] [ERROR] : Sending as text email since `lxml` is not installed
```
Reading the documentation it seems I need to specify that the 'feedback' is 'raw'
I am just not sure how to do this and I can't find any examples via google.
tia orotau

**Comment by kootenpv** [comment]
Wrap the contents with `yagmail.raw`: 

    contents = yagmail.raw(feedback)

Or you can just install lxml; `(sudo) pip install lxml` which would work in your case also...

**Comment by orotau** [comment]
Hi Pascal
I get the following error when I try that
AttributeError: 'module' object has no attribute 'raw'

g

On 15/09/15 19:08, Pascal van Kooten wrote:
>
> Wrap the contents with |yagmail.raw|:
>
> |contents = yagmail.raw(feedback) |
>
> Or you can just install lxml; |(sudo) pip install lxml| which would 
> work in your case also...
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/kootenpv/yagmail/issues/17#issuecomment-140300616>.
>

-- 
T : 021 081 71732

**Comment by kootenpv** [comment]
My bad, it was available as `yagmail.yagmail.raw`. Sorry for the inconvenience!

I now added it to the top level, so you should now be able to use `yagmail.raw` directly. 

You can obtain the new version by using `pip3 install -U yagmail` (or `pip ...`).

If it works for you, please close the issue :)

**Comment by orotau** [comment]
works well 
version is 0.4.114
Danke
