### ISSUE TITLE
[Question] What happens if you don't close the server?

### ISSUE THREAD

**Issue by Destaq** [kootenpv/yagmail#176]
I'm using `yagmail` for email forwarding on a Flask web application. Due to the nature of the application, I cannot close the `yagmail` server in the code, as I would then no longer receive emails. However, as I am testing this locally, when I `ctrl-c` the file, I'm not sure whether the yagmail server is still running.

If I stop the program, will the yagmail server continue to run locally? If so, is there a way to shut down its server?

**Comment by kootenpv** [comment]
When a program exits, for sure it will be cleaned.

In any case, no issue to keep it open.
