### ISSUE TITLE
Can I change the from field

### ISSUE THREAD

**Issue by MohdElBasyouni** [kootenpv/yagmail#182]
Hello,
Can I change the from field of the mail after creating a connection to the mail account ?
I need to use an alias configured on the connected account, please
Thanks

**Comment by RipperTs** [comment]
I need the same.

**Comment by RipperTs** [comment]
`yagmail.SMTP({'agent.smith@gmail.com': 'Agent Smith'})`

source： https://github.com/kootenpv/yagmail/issues/27#issuecomment-161422202
