### ISSUE TITLE
How do I show a custom name?

### ISSUE THREAD

**Issue by Tom1380** [kootenpv/yagmail#184]
I'm not sure how to express it in email terminology, but how can I send an email as `Organization <no-reply@organization.com>`, instead of just `no-reply@organization.com` ?
Thanks in advance for the help and for the nice library.

**Comment by kootenpv** [comment]
Search for alias

**Comment by Tom1380** [comment]
Maybe I just missed it, but I could only find examples of aliasing recipients, I would like for the recipient to see _me_ with an alias.

**Comment by Tom1380** [comment]
@kootenpv

**Comment by SleepAqua** [comment]
Merely use `yagmail.SMTP(user = {"no-reply@organization.com":  "Organization"}, **kwargs)`

**Comment by Tom1380** [comment]
Thanks @SleepAqua, worked perfectly.
