### ISSUE TITLE
No module named 'premailer'

### ISSUE THREAD

**Issue by lamhoson** [kootenpv/yagmail#189]
Anyone know how to fix this problem?

Error:
Warning: QtConsole does not support password mode, the text you type will be visible.
Password for <detaxxxxde01@gmail.com>: xxxx
Save username and password in keyring? [y/n]: y
No module named 'premailer'

Software versions:
yagmail                  ver. 0.14.245           
TF ver: 2.1.0  ,Keras ver= 2.2.4-tf 
Python: 3.7.9

**Comment by kootenpv** [comment]
Try pip install premailer

**Comment by lamhoson** [comment]
Thanks.
