### ISSUE TITLE
Successfully installed  but  import not   

### ISSUE THREAD

**Issue by coderliuhao** [kootenpv/yagmail#194]
Sysem: Ubuntu18.04
env : conda virtual enviroment
python version : 3.8.3

Error: I use 'pip install yagmail'  command  install  yagmail  default version 0.14.245 successfully,but  when I  run 'import yagmail ' in ipython shell.it  raised  "No module named  yagmail"

Hope for your help ,thx

**Comment by kootenpv** [comment]
Try in your ipython shell

    !pip install yagmail

probably you are trying to import it in not the same python as that you tried to install it
