### ISSUE TITLE
html strings not rendering

### ISSUE THREAD

**Issue by richiverse** [kootenpv/yagmail#2]
```python
#...
contents = ['<h1>This is a big title</h1>', ]
yag.send(
    to=to,
    subject='html test',
    contents=contents)
```

email gets sent but renders as plain text with html tags.

OS: ubuntu 14.04
python: pyenv 3.4
client: thunderbird

**Comment by kootenpv** [comment]
Thanks for filing the issue. I'm unable to reproduce it with the latest version, 0.3.72 (I do get a big titled title). Perhaps try upgrading with `sudo pip3 install -U yagmail`? Please let me know if that resolves the issue.

**Comment by kootenpv** [comment]
18 days later...
