### ISSUE TITLE
HTML sent is not what is received

### ISSUE THREAD

**Issue by oernster** [kootenpv/yagmail#20]
Using the code suggested here:
http://stackoverflow.com/questions/32911945/how-do-i-send-email-line-feeds-python-3-in-plain-text-mode-as-a-mime-alternate-w

I made slight modifications.  I used '' (empty string) as the filename.  Recipients was passed as a list instead of just one string. 

With my HTML I specified some CSS also which I wrapped in the HTML header.  It seems the CSS is ignored in the receive client; somehow it got mangled by yagmail.

I am passing this as HTML:

'css = <style>#stuff {border-radius: 25px;#etc..}</style>'

'safe_html = my_safe_html'

html ="<html><header>"+css+"</header><body>"+safe_html+"</body><html>"

'complete_html = add_styling(html, css)'

For the life of me I can't get the markdown here to display HTML code.  It says use a quote for inline code but that doesn't work.  Basically, though you probably can't see it, the css is in a header part of the HTML and the body is separated into a body part with div ids for the css tags (not included here).  It works, just not in yagmail.  Please use edit to see the gist.

**Comment by kootenpv** [comment]
Markdown: Try escaping `<` with `\` perhaps? I don't know. Or put ` characters around code.

Note that it is generally not possible to pass CSS in any emails (only `style` arguments could work). 
Link: https://css-tricks.com/using-css-in-html-emails-the-real-story/

Also, don't get confused by "filename"; it is just an optional format :)

You can fill the contents list with any amount/combination of strings, HTML code, file path images (inline), and  file path attachments.

Does that answer your questions?

**Comment by oernster** [comment]
I managed to get css working in an earlier incarnation of my non yagmail (the stackoverflow variant) code by inserting it into the header in style tags.  For the life of me I can't reproduce it now but I will chase it down and try and get that working with yagmail.

**Comment by oernster** [comment]
Having read your link and others on the interweb it seems HTML/CSS or images embedded in HTML have highly variable support in the massive selection of email clients available.  In fact the only thing that is supported most of the time is inline styling which is a pretty strong limitation.  I might end up going with pure text instead of MIMEMultipart/alternative given the complexities involved but I have yet to decide.  Thanks again.

**Comment by kootenpv** [comment]
Thanks for filing the issue!
