### ISSUE TITLE
Too few arguments?

### ISSUE THREAD

**Issue by namaneko** [kootenpv/yagmail#206]
I may be missing something but I can't seem to find much in the way of documentation on command line usage. I've used --help and come up with the following to send a message:

./yagmail -t goingout@gmail.com -s Test message -c This is the contents of my email. -u username.g

Every time it returns **error: too few arguments**.

What am I missing here?

**Comment by kootenpv** [comment]
Maybe try adding the from addr?

**Comment by namaneko** [comment]
Just tried that and I get:

yagmail: error: argument command: invalid choice: 'firerover.sync@gmail.com' (choose from 'oauth')

If I  add the -o option, I end up with **too few arguments** again.

**Comment by namaneko** [comment]
I know that there's a bit of configuration for yagmail when doing it from Python. Is there a way to configure it similarly from Terminal?

**Comment by kootenpv** [comment]
It looked broken to me indeed. Fixed...

Try upgrading:

    pip install --no-cache -U 0.14.248

I think then it will be good

**Comment by namaneko** [comment]
Alrighty. I tried that particular command and when I do it, I get the following:

Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting 0.14.248
  Could not find a version that satisfies the requirement 0.14.248 (from versions: )
No matching distribution found for 0.14.248

**Comment by namaneko** [comment]
I'm guessing that's due to my own delay in getting back. Did a pip install --upgrade yagmail and it looks like the packages have been updated.

Will try now.

THANK YOU!

**Comment by namaneko** [comment]
Well, now I can't get it to do anything. I get the following when running from the command line:

`Traceback (most recent call last):
  File "/home/pi/.local/bin/yagmail", line 6, in <module>
    from yagmail.__main__ import main
  File "/home/pi/.local/lib/python2.7/site-packages/yagmail/__init__.py", line 7, in <module>
    from yagmail.sender import SMTP
  File "/home/pi/.local/lib/python2.7/site-packages/yagmail/sender.py", line 14, in <module>
    from yagmail.message import prepare_message
  File "/home/pi/.local/lib/python2.7/site-packages/yagmail/message.py", line 66
    raise TypeError(f'{a} must be a valid filepath or file handle (instance of io.IOBase). {a} is of type {type(a)}')
                                                                                                                   ^
SyntaxError: invalid syntax
`

**Comment by abubelinha** [comment]
I also get the last error mentioned by @namaneko when I just try to import yagmail:

```Python
import yagmail

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\python34\lib\site-packages\yagmail\__init__.py", line 7, in <module>
    from yagmail.sender import SMTP
  File "c:\python34\lib\site-packages\yagmail\sender.py", line 14, in <module>
    from yagmail.message import prepare_message
  File "c:\python34\lib\site-packages\yagmail\message.py", line 66
raise TypeError(f'{a} must be a valid filepath or file handle (instance of io.IOBase). {a} is of type {type(a)}')
```

**Comment by giancampo** [comment]
Same here, any news about the last two messages? Thanks in advance,

**Comment by kootenpv** [comment]
Probably using too old python, perhaps try a newer python version?

**Comment by abubelinha** [comment]
Yes, it works now for me on Python 3.4, Windows XP. 
Thanks a lot!
