### ISSUE TITLE
Oauth instructions for using credential json file need update. Seemingly not relevant anymore

### ISSUE THREAD

**Issue by aa-dank** [kootenpv/yagmail#213]
This is in regards to this part of the documentation:
https://yagmail.readthedocs.io/en/latest/setup.html#using-oauth2

Tinkering with settings in the api dashboard, I could not get it to generate a json file that yagmail would accept.
For example the instruction link to this post:  https://blog.macuyiko.com/post/2016/how-to-send-html-mails-with-oauth2-and-gmail-in-python.html

...but there is no 'other' application type. According to this stackoverflow, that category has been replaced by 'desktop'
https://stackoverflow.com/questions/61984699/how-to-create-application-type-other-in-oauth-client-id-in-google

...but that creates a credential file that looks like this and is rejected by yagmail:
`client_secret_gmail.json:
{"installed":
{"client_id":"224588364290-8enok2fodado2rkrh26go11q3p11dbgi.apps.googleusercontent.com",
"project_id":"yagmail-oauth2",
"auth_uri":"https://accounts.google.com/o/oauth2/auth",
"token_uri":"https://oauth2.googleapis.com/token",
"auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs",
"client_secret":"-----------",
"redirect_uris":["urn:ietf:wg:oauth:2.0:oob",
"http://localhost"]}}`

I'm not sure there is a way to generate a usable creds.json file given the current limitations of the api dashboard.

**Comment by kootenpv** [comment]
Thank you! This indeed would require more investigation. It's great that you did so much already!

It would be interesting to find out if it is at all possible to accomplish this in python (getting the right scopes)

---

I can otherwise recommend the application-specific password method.

**Comment by NicDom** [comment]
To create a _.json_ file from the new format of the _credentials_ that **_yagmail_** accepts, it is sufficient to read out the _client ID_ and the _client secret_. If I change the code of 
```python
def get_oauth2_info(oauth2_file):
    ...

``` 
in [oath2.py](https://github.com/kootenpv/yagmail/blob/d6a5952c75c623fe932b78d75d64d07192697276/yagmail/oauth2.py#L101) as below, the script works properly again. Of course, optionally, you could also pass the username from [sender.py](https://github.com/kootenpv/yagmail/blob/master/yagmail/sender.py) to [oath2.py](https://github.com/kootenpv/yagmail/blob/master/yagmail/oauth2.py) as the _email_adress_  and thus you don't need to query it.
Here is the modified code (the additional lines go from `try` to `else`):
```python
def get_oauth2_info(oauth2_file):
    oauth2_file = os.path.expanduser(oauth2_file)
    if os.path.isfile(oauth2_file):
        with open(oauth2_file) as f:
            oauth2_info = json.load(f)

        try:
            oauth2_info = oauth2_info["installed"]
        except KeyError:
            return oauth2_info
        email_addr = input("Your 'email address': ")
        google_client_id = oauth2_info["client_id"]
        google_client_secret = oauth2_info["client_secret"]
        google_refresh_token, _, _ = get_authorization(google_client_id, google_client_secret)
        oauth2_info = {
            "email_address": email_addr,
            "google_client_id": google_client_id.strip(),
            "google_client_secret": google_client_secret.strip(),
            "google_refresh_token": google_refresh_token.strip(),
        }
        with open(oauth2_file, "w") as f:
            json.dump(oauth2_info, f)

    else:
        print("If you do not have an app registered for your email sending purposes, visit:")
        print("https://console.developers.google.com")
        print("and create a new project.\n")
        email_addr = input("Your 'email address': ")
        google_client_id = input("Your 'google_client_id': ")
        google_client_secret = getpass.getpass("Your 'google_client_secret': ")
        google_refresh_token, _, _ = get_authorization(google_client_id, google_client_secret)
        oauth2_info = {
            "email_address": email_addr,
            "google_client_id": google_client_id.strip(),
            "google_client_secret": google_client_secret.strip(),
            "google_refresh_token": google_refresh_token.strip(),
        }
        with open(oauth2_file, "w") as f:
            json.dump(oauth2_info, f)
    return oauth2_info
```

If you want I'll create a pull request.

**Comment by kootenpv** [comment]
Great work @NicDom! I have deployed a new version of yagmail.

You can upgrade using:

    pip install -U --no-cache yagmail>=0.14.260
