### ISSUE TITLE
AttributeError: module 'smtplib' has no attribute 'SMTP_SSL', no file on computer called 'email.py'

### ISSUE THREAD

**Issue by zoyt** [kootenpv/yagmail#215]
Hello,

I've been having a strange issue, and would love to hear y'all's thoughts:

I've got some code that works perfectly well as a .ipynb in VS code, rearranging some info, pulling the date, and emailing it to myself. Here's the yagmail part, with my details redacted:

> reciever = "myEmail@gmail.com"
    body = "details.htm"
    yag = yagmail.SMTP('myEmail@gmail.com','sixteenDigitCode')
    yag.send(
    to=receiver,
    subject="Details for {}".format(fullDate),
    contents=body

This code works in my notebook environment, where I was testing it, just fine. I receive the emails perfectly formatted, no issues at all. However, I was trying to get this set up on in Task Scheduler on Win10, so I put my code into a .py, and was setting up a .bat to execute. Much to my suprise though, when I run the same code as a .py that I just did as a .ipynb, I get the following error (again with my details removed):

> PS C:\Users\Zoyt\dev\Jupyter Projects> & "C:/Users/Zoyt/Anaconda3/python.exe" "c:/Users/
    Zoyt/dev/Jupyter Projects/mail_server/test.py"
    Traceback (most recent call last):
    File "c:/Users/Zoyt/dev/Jupyter Projects/mail_server/test.py", line 5, in <module>
    yag.send('myEmail@gmail.com', 'subject', contents)
    File "C:\Users\Zoyt\Anaconda3\lib\site-packages\yagmail\sender.py", line 153, in send
    self.login()
    File "C:\Users\Zoyt\Anaconda3\lib\site-packages\yagmail\sender.py", line 206, in login
    self._login(self.credentials)
    File "C:\Users\Zoyt\Anaconda3\lib\site-packages\yagmail\sender.py", line 213, in _login
    self.smtp = self.connection(self.host, self.port, **self.kwargs)
    File "C:\Users\Zoyt\Anaconda3\lib\site-packages\yagmail\sender.py", line 76, in connection
    return smtplib.SMTP_SSL if self.ssl else smtplib.SMTP
    AttributeError: module 'smtplib' has no attribute 'SMTP_SSL'

I've been poking at this problem for a while, and most things I've found online point to this being an issue with another file being called "email.py." I have scoured my computer, and have not found any file called "email.py," much less in the same directory that I am working in. 

If it is helpful, I am running Python 3.8.8 64-bit. 

Thank you!

Zoyt

**Comment by kootenpv** [comment]
maybe try updating the version

**Comment by zoyt** [comment]
Hm, no luck there. Tried updating both the python version (to 3.9.6) and making sure I have the most recent version of yagmail by reinstalling. I would really love to get this working, anything else you think I should try?

**Comment by kootenpv** [comment]
Hmmm, try:

```python
pascal@x1x:/home/pascal$ python
Python 3.9.7 (default, Aug 31 2021, 13:28:12) 
[GCC 11.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from smtplib import SMTP_SSL
```

**Comment by zoyt** [comment]
weirdly similar problem, works fine as a notebook cell, but not in the cli:
```
PS C:\Users\Zoyt\dev\Jupyter_Projects> & "C:/Users/Zoyt/Anaconda3/envs/py395/python.exe" "c:/Users/Zoyt/dev/Jupyter_Projects/mail_server/runserver.py"
Traceback (most recent call last):
  File "c:\Users\Zoyt\dev\Jupyter_Projects\mail_server\runserver.py", line 1, in <module>
    from smtplib import SMTP_SSL
ImportError: cannot import name 'SMTP_SSL' from 'smtplib' (C:\Users\Zoyt\Anaconda3\envs\py395\lib\smtplib.py) 
```

**Comment by kootenpv** [comment]
Can only imagine this https://stackoverflow.com/questions/32056109/importerror-cannot-import-name-smtp-ssl

**Comment by zoyt** [comment]
Wild. I used to have a file called email.py in a different directory in a random library that installed with Anaconda, but early on while troubleshooting I changed the name of it, just in case it was somehow interfering. 

Is it possible that I have something else that is named in a way that is confusing python? I've got a file or two called test.py from my early days, but those are in different directories and have never been an issue before. If there's a known list, I can run through and make sure nothing fishy is going on.

**Comment by watchpoints** [comment]
install python

yum install epel-release

dnf remove python3

dnf install  python3.11

**Comment by aknwe** [comment]
I have the same problem,and I am running Python 3.10 64-bit.By the way,I only import smtplib,so it may just be the error of smtplib.

**Comment by kootenpv** [comment]
other possibility is when you have a script called `email.py`

**Comment by aknwe** [comment]
> other possibility is when you have a script called `email.py`

no,I don't have the script.and my problem has been solved by lowering the Python version level to 3.7.

**Comment by kootenpv** [comment]
> > other possibility is when you have a script called `email.py`
> 
> no,I don't have the script.and my problem has been solved by lowering the Python version level to 3.7.

yagmail is known to work with 3.10+ so I'm guessing that in this case a fresh install might have helped
