### ISSUE TITLE
import yagmail -> error

### ISSUE THREAD

**Issue by speedy-10** [kootenpv/yagmail#222]
Hi I installed yagmail at first with:

`~$ pip3 install yagmail[all]
Collecting yagmail[all]
  Downloading yagmail-0.15.277-py2.py3-none-any.whl (17 kB)
Collecting premailer
  Downloading premailer-3.10.0-py2.py3-none-any.whl (19 kB)
Requirement already satisfied: keyring; extra == "all" in /usr/lib/python3/dist-packages (from yagmail[all]) (18.0.1)
Collecting dkimpy; extra == "all"
  Downloading dkimpy-1.0.5.tar.gz (59 kB)
     |████████████████████████████████| 59 kB 1.3 MB/s 
Collecting cssselect
  Downloading cssselect-1.1.0-py2.py3-none-any.whl (16 kB)
Collecting cssutils
  Downloading cssutils-2.3.0-py3-none-any.whl (404 kB)
     |████████████████████████████████| 404 kB 1.3 MB/s 
Collecting cachetools
  Downloading cachetools-5.0.0-py3-none-any.whl (9.1 kB)
Requirement already satisfied: lxml in /usr/lib/python3/dist-packages (from premailer->yagmail[all]) (4.5.0)
Requirement already satisfied: requests in ./.local/lib/python3.8/site-packages (from premailer->yagmail[all]) (2.24.0)
Requirement already satisfied: secretstorage in /usr/lib/python3/dist-packages (from keyring; extra == "all"->yagmail[all]) (2.3.1)
Collecting dnspython>=1.16.0
  Downloading dnspython-2.2.0-py3-none-any.whl (266 kB)
     |████████████████████████████████| 266 kB 1.3 MB/s 
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/lib/python3/dist-packages (from requests->premailer->yagmail[all]) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/lib/python3/dist-packages (from requests->premailer->yagmail[all]) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/lib/python3/dist-packages (from requests->premailer->yagmail[all]) (1.25.8)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests->premailer->yagmail[all]) (2019.11.28)
Building wheels for collected packages: dkimpy
  Building wheel for dkimpy (setup.py) ... done
  Created wheel for dkimpy: filename=dkimpy-1.0.5-py3-none-any.whl size=48737 sha256=8227bdf943cd0ec058b41da89a9c020c0114c427167adfb3901bb39cc591d995
  Stored in directory: /home/USER/.cache/pip/wheels/92/37/be/38fa78084212ea3f447bcf32d383a86001dddae6067a142d91
Successfully built dkimpy
Installing collected packages: cssselect, cssutils, cachetools, premailer, dnspython, dkimpy, yagmail
  WARNING: The scripts csscapture, csscombine and cssparse are installed in '/home/USER/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts arcsign, arcverify, dkimsign, dkimverify and dknewkey are installed in '/home/USER/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script yagmail is installed in '/home/USER/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed cachetools-5.0.0 cssselect-1.1.0 cssutils-2.3.0 dkimpy-1.0.5 dnspython-2.2.0 premailer-3.10.0 yagmail-0.15.277
`

After that I tried the following in in a thonny-shell:

`>>> import yagmail
Traceback (most recent call last):
  File "<pyshell>", line 1, in <module>
ModuleNotFoundError: No module named 'yagmail'
`

Another attempt was using:
`pip3 install -e git+https://github.com/kootenpv/yagmail#egg=yagmail[all]
`
Which doen't solve the issue.

May system:
- Ubuntu 20.04, Kernel: 5.13.0-27-generic x86_64
- Python 3.7.9

How could I use yagmail ?

**Comment by kootenpv** [comment]
Could you perhaps try an earlier version from pypi

pip install yagmail==0.14.261

**Comment by speedy-10** [comment]
Hi, I tried, but it didn't work:
`
Fr 21. Jan 07:34:28 CET 2022
USER@USER-desktop:~$ pip uninstall yagmail
Found existing installation: yagmail 0.15.0
Uninstalling yagmail-0.15.0:
  Would remove:
    /home/USER/.local/lib/python3.8/site-packages/yagmail.egg-link
Proceed (y/n)? 
Your response ('') was not one of the expected responses: y, n
Proceed (y/n)? y
  Successfully uninstalled yagmail-0.15.0
USER@USER-desktop:~$ pip3 uninstall yagmail
WARNING: Skipping yagmail as it is not installed.
USER@USER-desktop:~$ pip install yagmail==0.14.261
Collecting yagmail==0.14.261
  Downloading yagmail-0.14.261-py2.py3-none-any.whl (16 kB)
Requirement already satisfied: premailer in ./.local/lib/python3.8/site-packages (from yagmail==0.14.261) (3.10.0)
Requirement already satisfied: cachetools in ./.local/lib/python3.8/site-packages (from premailer->yagmail==0.14.261) (5.0.0)
Requirement already satisfied: requests in ./.local/lib/python3.8/site-packages (from premailer->yagmail==0.14.261) (2.24.0)
Requirement already satisfied: cssutils in ./.local/lib/python3.8/site-packages (from premailer->yagmail==0.14.261) (2.3.0)
Requirement already satisfied: cssselect in ./.local/lib/python3.8/site-packages (from premailer->yagmail==0.14.261) (1.1.0)
Requirement already satisfied: lxml in /usr/lib/python3/dist-packages (from premailer->yagmail==0.14.261) (4.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests->premailer->yagmail==0.14.261) (2019.11.28)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/lib/python3/dist-packages (from requests->premailer->yagmail==0.14.261) (1.25.8)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/lib/python3/dist-packages (from requests->premailer->yagmail==0.14.261) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/lib/python3/dist-packages (from requests->premailer->yagmail==0.14.261) (2.8)
Installing collected packages: yagmail
  WARNING: The script yagmail is installed in '/home/USER/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed yagmail-0.14.261
USER@USER-desktop:~$ 
`

**Comment by speedy-10** [comment]
EDIT: 
It didn't work with Thonny, but using IDLE, it works to import yagmail.
