### ISSUE TITLE
Please consider that  msg["From"] can be customized

### ISSUE THREAD

**Issue by coolkit-carl** [kootenpv/yagmail#229]
This is very common. We use professional email services (such as mailgun). They usually provide us with an account with a slightly different brand name. We need to customize the sender.

**Comment by leffss** [comment]
```
...
mail_user = {'test@test.com': 'your_alias_name'} 
yag = yagmail.SMTP(user=mail_user, password=mail_pass, host=mail_host, port=mail_ssl_port, smtp_ssl=True)
...
```
