### ISSUE TITLE
BCC's visible to recipients

### ISSUE THREAD

**Issue by ElvoRoveli** [kootenpv/yagmail#23]
I've found that when I send a message using `bcc = [...]`, the full BCC list is visible to all recipients.

**Comment by kootenpv** [comment]
Very much verified! My sincerest apologies if it caused any harm. 

Should be fixed as of 0.4.115. You should run `pip install -U yagmail` to update.

**Comment by kootenpv** [comment]
Fixed as of `0.4.116`. Note that you will still see the BCC when you use

    to="myemail@gmail.com", bcc="someother@gmail.com"

Since you are sending to yourself, it still shows the BCC. If you send it to someone else though, then no one will see the BCC.

Update using `pip install -U yagmail` should do the trick
