### ISSUE TITLE
Attribute error when importing yagmail

### ISSUE THREAD

**Issue by TechWiz-3** [kootenpv/yagmail#233]
I'm using `Python 3.9.0` on MacOS `Mojave 10.14.6`
I installed yagmail using `pip install yagmail[all]`
I'm having an error when attempting to import yagmail
```py
>>> import yagmail
Exception ignored in: <function Client.__del__ at 0x108843790>
Traceback (most recent call last):
  File "/Users/Peregrine/Library/Python/3.9/lib/python/site-packages/httpx/_client.py", line 1139, in __del__
    self.close()
  File "/Users/Peregrine/Library/Python/3.9/lib/python/site-packages/httpx/_client.py", line 1111, in close
    self._transport.close()
AttributeError: 'Client' object has no attribute '_transport'
```
Any help would be much appreciated

**Comment by TechWiz-3** [comment]
I tested yagmail on a Ubuntu VM and didn't have any errors, is the error something to do with my OS version?

**Comment by kootenpv** [comment]
it mentions loading `httpx` - this should not be loaded in yagmail, maybe that's related

possibly the name of your script

**Comment by TechWiz-3** [comment]
My script actually doesn't have a name, I'm using the python prompt thingy in the terminal.

**Comment by TechWiz-3** [comment]
Not sure how the error could show up if yagmail doesn't use httpx tho 😅

**Comment by kootenpv** [comment]
could you maybe create a new folder without any files in there and then start python and try again?

**Comment by kootenpv** [comment]
also maybe try to reinstall without `[all]`

**Comment by kootenpv** [comment]
maybe try uninstall and installing httpx again?

**Comment by TechWiz-3** [comment]
Thanks a lot, updating httpx worked, now i can import yagmail without any errors :)
