### ISSUE TITLE
HTTP error 400 at call_refresh_token

### ISSUE THREAD

**Issue by GrzegorzKowalik** [kootenpv/yagmail#237]
Hi, I'm using oAuth to authenticate to Gmail.

I'm struck with the same issue described in https://github.com/kootenpv/yagmail/issues/181 and https://github.com/kootenpv/yagmail/issues/211.

The problem is the solution proposed in those issues is no longer valid - since 30.05.2022 enabling less secure apps is disabled in google account settings, and overall I want to stick to oAuth. 

This issue only appears after a few days of working okay. The only workaround I found is to create and use new oAuth credentials in Google platform console

**Comment by kootenpv** [comment]
Hmmm wonder if there's a new api.

In any case I recommend now application specific password
