### ISSUE TITLE
Less secure apps no longer allowed

### ISSUE THREAD

**Issue by andydish** [kootenpv/yagmail#238]
Google has updated their policy on allowing less secure apps:
![image](https://user-images.githubusercontent.com/22012295/172871330-95f400e2-b869-4636-a018-972271f3d189.png)
That means the typical way of getting yagmail to work by allowing less secure apps is no longer possible. Are there plans to support more secure yagmail?

**Comment by kootenpv** [comment]
Hmm, I think it still works for me? Maybe what has changed is to require 2fa to generate app specific password
