### ISSUE TITLE
Less secuirty app option disabled from June 2022

### ISSUE THREAD

**Issue by tomnewg** [kootenpv/yagmail#239]
Hi all,

gmail has disabled the "Less secure apps" functionality. Therefore yagmail is not working anymore for gmail. 
Is there a way around it? Does yagmail need an upgrade or will it just not be possible going forward to use yagmail for gmail accounts?

Many thanks for your help

Tom

**Comment by tomnewg** [comment]
Just to add, I did try to add an "App password" but I still get the same error.

https://stackoverflow.com/questions/72478573/sending-and-email-using-python-problem-causes-by-last-google-policy-update

**Comment by safelysparky** [comment]
same issue here

**Comment by safelysparky** [comment]
@tomnewg just set up the app password in google account security and replace the old email password with the app password  (a long sequence of letters, do not forget to copy it before close the window!) in your code, then it works fine now in yagmail. During the app password setup, make sure the app you selected is mail, also the device you selected matches the machine on which your code is running (e.g. window computer). I hope this helps!

**Comment by tomnewg** [comment]
thanks for your comment. As mentioned in my second comment I tried this multiple times. I am still getting the error:
"SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials n123-20020a1c2781000000b0039c63f4bce0sm13818407wmn.12 - gsmtp')
"
