### ISSUE TITLE
Less secure apps isn't possible any more - how to bypass/alternative

### ISSUE THREAD

**Issue by stodla123** [kootenpv/yagmail#241]
Hello i have a question:

my raspi used to send automated emails - but now it stopped working.

  File "/usr/lib/python3.9/smtplib.py", line 646, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  

then i found this on googles own help site:
++++++++++++++++++++++++++++++++++++++++++++++++++

Less secure apps & your Google Account
To help keep your account secure, from May 30, 2022, ​​Google no longer supports the use of third-party apps or devices which ask you to sign in to your Google Account using only your username and password.

Important: This deadline does not apply to Google Workspace or Google Cloud Identity customers. The enforcement date for these customers will be announced on the Workspace blog at a later date.

For more information, continue to read.
++++++++++++++++++++++++++++++++++++++++++++++++++

how can i make it work again?

thank you in advance.

regards Stefan

**Comment by kootenpv** [comment]
I think here https://support.google.com/accounts/answer/185833

**Comment by ericoneal** [comment]
This worked for me.
