### ISSUE TITLE
html tags yandex

### ISSUE THREAD

**Issue by Exzentttt** [kootenpv/yagmail#246]
I ran into a problem that in yandex by mail in the preview html tags, but in the letter itself the correct mail. I don't see such problems in gmail, can someone tell me?

Preview:
<img width="498" alt="Снимок экрана 2022-08-08 в 15 23 02" src="https://user-images.githubusercontent.com/41418703/183417180-419ca624-f1ff-4257-871f-e12b6d3fcd78.png">

Mail:
<img width="967" alt="image" src="https://user-images.githubusercontent.com/41418703/183417519-829fc6d9-c739-40fe-8258-2891971e0ccc.png">

**Comment by kootenpv** [comment]
preview shows the raw version mail shows html version, pretty common, nothing to worry about
