### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by tjerram** [kootenpv/yagmail#257]
I am using  pip3 install yagmail

I get the following error:

  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/yagmail/

any Ideas"

**Comment by kootenpv** [comment]
Just try it again, seems like your network was down

**Comment by tjerram** [comment]
Nope, it's not the network conntctio.  i can ping pypi.org

Tom Jerram
(607) 235-0316

**Comment by kootenpv** [comment]
It simply works from my machines, so still believe it's something with your configuration.

Which OS? Which Python version? What network?

Maybe you can confirm this does not work for you on another machine...

**Comment by tjerram** [comment]
I reinstalled the raspberry pi os and I can now install it.
