### ISSUE TITLE
From: mymail@gmail.com

### ISSUE THREAD

**Issue by schef** [kootenpv/yagmail#27]
When i send mail it does not show my name.
```
mymail@gmail.com <mymail@gmail.com>
```

**Comment by kootenpv** [comment]
What does it show?

You can specifically set alias like:

    yag = yagmail.SMTP({'mymail@gmail.com': 'myalias'}, 'pass')

**Comment by schef** [comment]
It shows my mail address.
Yes. Now it shows the name. I coudn't find that in documentation.
Thanks.

**Comment by kootenpv** [comment]
@schef It's indeed in a silly place, but it's there, look at https://github.com/kootenpv/yagmail/blob/master/README.md#errors `YagAddressError`

**Comment by schef** [comment]
You are right! I searched the repo with From and could not find it. :+1:
