### ISSUE TITLE
Setting Reply-To: different than From:

### ISSUE THREAD

**Issue by deweydb** [kootenpv/yagmail#33]
Is this possible? i can't see anything in the docs about it.

**Comment by kootenpv** [comment]
It is not possible to set "From". I suppose that would only make sense for local SMTP testing. Note that gmail actually might block for trying to spoof the "From" header.

Actually, "Reply-To" header is not included. Perhaps you would consider writing a test case / code how you'd like it? You could even go for a pull-request if you wanted to.

Thanks for taking the time to make "an issue" out of it :-).

**Comment by kootenpv** [comment]
Actually, on `yag.send()` you can add an argument `headers=` which are additional headers to be sent. You could try it.

**Comment by bepetersn** [comment]
I think using headers will work, as that's the way I did it before I used yagmail. Still, I'd also like to be able to specify `reply_to` as a kwarg, just like `cc` and `bcc`... I might try to make a pull request (with tests) one of these days.

**Comment by kootenpv** [comment]
Great suggestion! PR is very much encouraged.

**Comment by vincenthawke** [comment]
Did this PR ever happen? Came here to solve the same issue @bepetersn had. And I already tested modifying yagmail by implementing From spoofing and you were right, @kootenpv Gmail blocked it and email never arrived. Reply-To is all I really need and it will solve my problem where web server redirects user messages to my Gmail and I can reply them form there, by clicking Reply directly and not having to modify the recipient.
