### ISSUE TITLE
using yagmail.smtp(), pyCharm asks for 'keyrings.alt'

### ISSUE THREAD

**Issue by DanielTimLee** [kootenpv/yagmail#38]
Before reporting some issues, I'd like to thanks so much for making this module!
I was using Flask-mail, and there was some trouble with using it.
(it's last updated date was about 2 years ago , so i moved on to Yagmail!)

I was having some troubles with yagmail connections, so i changed my code like this. (left -> right)
(for some reason, it **sometimes** prints "**[Error] Please run Connect() first**" - maybe connection timed out?) 
![image](https://cloud.githubusercontent.com/assets/16421480/14816472/0fdd6c12-0bec-11e6-88cb-71ac760cb99d.png)
![image](https://cloud.githubusercontent.com/assets/16421480/14816588/b19c093c-0bec-11e6-9f41-0b168afd6346.png)

by changing this (one-liner) there were no more errors, but my pyCharm keeps prints "package requirement message." (though it works well!)

![image](https://cloud.githubusercontent.com/assets/16421480/14816432/d1c101f0-0beb-11e6-90d4-dbcb39de2dac.png)

my question is 
1.Why the Connect error occurs?
2.Why there is package requirement message?

**Comment by kootenpv** [comment]
Hi, thanks! Did you try registering only once though? For the registration you indeed need to have `keyring` installed. Do you use windows?

**Comment by DanielTimLee** [comment]
No, i use mac 10.10 yosemite.

Eventhough i don't have keyring installed, it works fine!!
And i wonder why it is...?

**Comment by kootenpv** [comment]
Maybe pycharm is using a different version there? I suppose the keyring package has been installed anyway on Mac.

**Comment by DanielTimLee** [comment]
Is there any chance that keyring does the same function for the keyring.alt **automatically**?
(even if i didn't specifiyed that "yagmail will uses keyring alternative for keyring.alt")

Because I don't have Keyring.alt but Only Keyring.

**Comment by kootenpv** [comment]
You can give a timeout which will be passed to SMTP on creating `yagmail.SMTP(timeout=10)` if that's what you mean?

**Comment by DanielTimLee** [comment]
Not actually... but thanks for the answer!!

I was wandering if there is any default value for the timeout. ^^
