### ISSUE TITLE
Adding from string

### ISSUE THREAD

**Issue by BusinessTec** [kootenpv/yagmail#4]
I have a fully functioning setup (BTW: great package!). I am not able only to add one point from my test list, adding name of the sender, next to  email address itself. Is it possible in the current version?

**Comment by kootenpv** [comment]
Hey!

I think what you're looking for is to give an alias? It's in the documentation, but I'lll also post it here:

    to1 = email1@example.com
    to2 = email2@example.com
    yag.send(to = to) 
    yag.send(to = [to, to2]) # List or tuples for emailadresses *without* aliases
    yag.send(to = {to : 'John'}) # Dictionary for emailaddress *with* aliases
    yag.send(to = {to : John', to2 : 'Alice'}

**Comment by kootenpv** [comment]
Wow, indeed, there was a bug! The result was sending to the right person, but with a wrong alias (you became the alias, very bad!). You will want to upgrade to the new version.

    pip install -U yagmail
    pip3 install -U yagmail

**Comment by BusinessTec** [comment]
Actually I am trying to do the same but 'from' rather then 'to' - tried all combinations but it did not work. Will try with a new version!

**Comment by kootenpv** [comment]
You were right! Apparently it is required to use 'Alias <email>' and you can't just use alias. Funny. Please try again! 

    yagmail.Connect({'your@email.com' : 'youralias'}).send()

**Comment by BusinessTec** [comment]
It works now - thanks a lot for fixing it!

**Comment by kootenpv** [comment]
You're welcome
