### ISSUE TITLE
tables get extra elements attached

### ISSUE THREAD

**Issue by amn41** [kootenpv/yagmail#40]
see this question on SO 
http://stackoverflow.com/questions/36954801/python-yagmail-table-extra-td-tags-in-table

**Comment by kootenpv** [comment]
I'll answer it there, and copy the "final answer" here.

**Comment by amn41** [comment]
as far as I can tell this is getting added by the gmail web client - it's not present in the raw form of the email (so has nothing to do with yagmail). so closing
