### ISSUE TITLE
issues with keyring dependency

### ISSUE THREAD

**Issue by wlbentley** [kootenpv/yagmail#41]
Trying out yagmail on OS X El Capitan, Python 2.7.

I'm prevented from evaluating yagmail by errors coming from keyring. See [https://github.com/jaraco/keyring/issues/219](https://github.com/jaraco/keyring/issues/219).

Yagmail correctly retrieved the password once.

[Edit:] Yagmail/keyring works correctly outside of the virtualenv. This is a virtualenv issue.

**Comment by kootenpv** [comment]
If you give a password to `SMTP()` you can avoid keyring. Not ideal, but at least it can work like that. I have the idea it might be a keyring issue.

**Comment by wlbentley** [comment]
Thanks.
