### ISSUE TITLE
ValueError: stat: path too long for Windows

### ISSUE THREAD

**Issue by Dylan-Chapman** [kootenpv/yagmail#44]
I'm sending a long-ish email (HTML) and am receiving this error when sending on Windows. I'm assuming this happens because of Windows file path limit and because, as the README says, the contents argument 'will try to see if the content (string) can be read as a file locally, e.g. '/path/to/image.png''.

The last few entries from the traceback are

```
...
  File "[path]\yagmail\yagmail.py", line 98, in send
    msg = self._prepare_message(addresses, subject, contents, attachments, headers)
  File "[path]\yagmail\yagmail.py", line 217, in _prepare_message
    has_included_images, content_objects = self._prepare_contents(contents)
  File "[path]\yagmail\yagmail.py", line 276, in _prepare_contents
    content_object = self._get_mime_object(content)
  File "[path]\yagmail\yagmail.py", line 347, in _get_mime_object
    if os.path.isfile(content_string) and not is_raw:
  File "[path]\lib\genericpath.py", line 30, in isfile
    st = os.stat(path)
ValueError: stat: path too long for Windows
```

Is there a way to get around this?

**Comment by kootenpv** [comment]
Ah, I switched `is_raw` check and `os.path` check (which apparently does not work for windows).
In your case, you can safeguard your contents with "raw" as in:

    yag.send(contents=yagmail.raw(html_text))

But I'm not happy how that looks like...

Are you sending scraped contents or a file? If a file, you could of course send the file directly.

**Comment by Dylan-Chapman** [comment]
Thankfully I'm just sending an HTML list (scraped contents), so I can convert it to line-by-line text and send it with raw.

Glancing at the code, I'm not sure of a solution off the top of my head either. Unfortunately I'm still in the midst of learning Python.

**Comment by luisa123456** [comment]
Long Path tool can resolve error messages like: path too long, cannot delete file, destination path is too long, etc. It also helps you to remove blocked files. You can easily fix file errors with this software.

**Comment by rajat-np** [comment]
@kootenpv I tried using yagmail.raw() , and it's working. :)
