### ISSUE TITLE
import yagmail

### ISSUE THREAD

**Issue by rich7** [kootenpv/yagmail#45]
As noob I tried yagmail. But I got pretty fast stuckted in an error
I installed both 
pip install yagmail
pip3 install yagmail

Ended in:
Successfully installed yagmail keyring secretstorage pycrypto
Cleaning up...

then I copied the example as provide 

```
import yagmail

yag = yagmail.SMTP('xxxxx_pz@top10top.com', 'xxxxx').send('richard_xxxx@yahoo.com', 'subject', 'This is the body')

```

With this as result.

 File "test.py", line 1, in <module>
    import yagmail
ImportError: No module named yagmail

 Tried serveral things like starting from different directories.. 
Any clue how to solve this?

**Comment by kootenpv** [comment]
Which python version are you running? E.g. do you start python with `python` or with `python3`?

**Comment by rich7** [comment]
ok start with python3 does the job, thank you for your fast answer
