### ISSUE TITLE
Weirdness with smtp_skip_login

### ISSUE THREAD

**Issue by nfg** [kootenpv/yagmail#53]
Hello!

I'm trying out yagmail at work. We have an internal SMTP server without any authentication, so when I instantiate the object, I have to pass in a true value for smtp_skip_login. However, when I send a message, I get an error like...

```
send: 'mail FROM:<@gmail.com> size=1089\r\n'
reply: '501 5.1.7 Invalid address\r\n'
reply: retcode (501); Msg: 5.1.7 Invalid address
```

From looking at the code, it looks like passing in smtp_skip_login wipes out user, and then self.user and self.useralias are set improperly. I can get around it by manually setting those two attributes after construction, but that seems weird.

Why is the constructor getting rid of the user data in this case? Am I doing something wrong?

Cheers!

**Comment by kootenpv** [comment]
Hey, thanks for posting! I think it was a short term hack to test out skipping login for internal servers, actually. I didn't really use it myself, so it really is untested. You nicely pointed me to the spot though. I guess it would be nice if you'd be involved on the local server side :))))
Perhaps adding more tests to yagmail (would be really nice if we would choose a nice local server for actually sending mails and testing headers or something). Would you be interested?

As for your issue:

```
if smtp_skip_login:
    user = ''
elif user is None:
    user = self._find_user_home_path()
```

I think if we make that `if smtp_skip_login and user is None` then that would work for now. I'll implement it, upload a new version, and then maybe you could confirm whether it works for your specific case?

Best regards,
Pascal

**Comment by nfg** [comment]
Hiya! I tested it out, and it sends! However, in Thunderbird the email shows up as from "yagmailtest@ <"WORK.com yagmailtest"@WORK.com>". I'm not sure if that's a Thunderbird thing, or if something else is going on.

Here's how I construct the object:

````
yag = yagmail.SMTP(user='yagmailtest@WORK.com', host='mail.WORK.com', password=None, smtp_skip_login=True, smtp_set_debuglevel=1)

print yag.user # yagmailtest@WORK.com
print yag.useralias # yagmailtest@WORK.com
````

OK so far. But the payload looks like...

````
send: 'mail FROM:<yagmailtest@WORK.com> size=1109\r\n'
reply: '250 2.1.0 Sender OK\r\n'
reply: retcode (250); Msg: 2.1.0 Sender OK
send: 'rcpt TO:<nigelg@WORK.com>\r\n'
reply: '250 2.1.5 Recipient OK\r\n'
reply: retcode (250); Msg: 2.1.5 Recipient OK
send: 'data\r\n'
reply: '354 Start mail input; end with <CRLF>.<CRLF>\r\n'
reply: retcode (354); Msg: Start mail input; end with <CRLF>.<CRLF>
data: (354, 'Start mail input; end with <CRLF>.<CRLF>')
send: 'Content-Type: multipart/mixed; boundary="===============4512797292882096510=="\r\nMIME-Version: 1.0\r\nSubject: YARR YAGMAIL TEST\r\nFrom: yagmailtest@WORK.com <yagmailtest@WORK.com>\r\nTo: nigelg@WORK.com\r\n\r\n--===============4512797292882096510==\r\nContent-Type: multipart/alternative;\r\n boundary="===============6803675811795910510=="\r\nMIME-Version: 1.0\r\n\r\n--===============6803675811795910510==\r\nContent-Type: text/plain; charset="utf-8"\r\nMIME-Version: 1.0\r\nContent-Transfer-Encoding: base64\r\n\r\nPGJyPjxicj4gICAgVGhpcyBpcyBhIG11bHRpbGluZSB0ZXN0IG1lc3NhZ2U8YnI+PGJyPiAgICBX\r\nT1JTSElQIE1FISE8YnI+PGJyPiAgICA=\r\n\r\n--===============6803675811795910510==\r\nContent-Type: multipart/related;\r\n boundary="===============5787630365189408559=="\r\nMIME-Version: 1.0\r\n\r\n--===============5787630365189408559==\r\nContent-Type: text/html; charset="utf-8"\r\nMIME-Version: 1.0\r\nContent-Transfer-Encoding: base64\r\n\r\nPGRpdj48YnI+PGJyPiAgICBUaGlzIGlzIGEgbXVsdGlsaW5lIHRlc3QgbWVzc2FnZTxicj48YnI+\r\nICAgIFdPUlNISVAgTUUhITxicj48YnI+ICAgIDwvZGl2Pg==\r\n\r\n--===============5787630365189408559==--\r\n\r\n--===============6803675811795910510==--\r\n\r\n--===============4512797292882096510==--\r\n.\r\n'
reply: '250 2.6.0 <XXXXXXXXX@exchange.WORK> [InternalId=16578075] Queued mail for delivery\r\n'
reply: retcode (250); Msg: 2.6.0 <XXXXXXXXX@exchange.WORK> [InternalId=16578075] Queued mail for delivery
data: (250, '2.6.0 <XXXXXXXXX@exchange.WORK> [InternalId=16578075] Queued mail for delivery')
send: 'quit\r\n'
reply: '221 2.0.0 Service closing transmission channel\r\n'
reply: retcode (221); Msg: 2.0.0 Service closing transmission channel
````

Again, I'm not sure if it's a yagmail thing or Thunderbird.

Cheers!

**Comment by kootenpv** [comment]
Thanks for following up! Thunderbird also hasn't received any focus :) Your construction looks fine. I found the issue, it's getting nasty enough to warrant a new function.
On further inspection: it actually is not a bug; it has been how it is "intended".
If you do not set an alias, the header would become:

    email <email>

Which is pretty awkward indeed... but we wouldn't be able to get contact info (to create something like `name <email>`. So I think, even though awkward, it's the best we can do.

So that means it should all be working!

---

I actually do not see the problem with the payload?

**Comment by nfg** [comment]
Hey! Sorry for the delayed response.

I did some reading and

```
From: yagmailtest@WORK.com <yagmailtest@WORK.com>
```

is encoded incorrectly. According to https://www.ietf.org/rfc/rfc2822.txt , the from field should match:

```
from            =       "From:" mailbox-list CRLF
mailbox-list    =       (mailbox *("," mailbox)) / obs-mbox-list
obs-mbox-list   =       1*([mailbox] [CFWS] "," [CFWS]) [mailbox]
mailbox         =       name-addr / addr-spec
addr-spec       =       local-part "@" domain     ; gonna ignore this now because that's the email bit

name-addr       =       [display-name] angle-addr
angle-addr      =       [CFWS] "<" addr-spec ">" [CFWS] / obs-angle-addr   ; OK, so this is the <email@address> 

display-name    =       phrase
obs-phrase      =       word *(word / "." / CFWS)
word            =       atom / quoted-string
atom            =       [CFWS] 1*atext [CFWS]
atext           =       ALPHA / DIGIT / ; Any character except controls,
                        "!" / "#" /     ;  SP, and specials.
                        "$" / "%" /     ;  Used for atoms
                        "&" / "'" /
                        "*" / "+" /
                        "-" / "/" /
                        "=" / "?" /
                        "^" / "_" /
                        "`" / "{" /
                        "|" / "}" /
                        "~"
```

So, if I read all that correctly, having a @ in the display-name is only valid if the display-name is enclosed in quotation marks. Once I add the quotation marks, the display-name shows under in my email clients as "yagmailtest@WORK.com".

POSTFIX: Doh, I was looking at the wrong RFC! The current one in this case is https://tools.ietf.org/html/rfc5322 . I skimmed through, and the grammar for display-name should be the same.

**Comment by kootenpv** [comment]
Wow, that's great. Thanks for the actual research! What about for an alias to check whether "@" is in it, and if so, add quotes? Sounds like that simple logic would go a long way?

**Comment by nfg** [comment]
Hmm. Yeah, I like that idea better. One sec, I'll redo my PR.

**Comment by nfg** [comment]
Should be grand with PR #55 !
