### ISSUE TITLE
Failed to install yagmail on android 2.3.6

### ISSUE THREAD

**Issue by dimashi** [kootenpv/yagmail#64]
I was trying to install yagmail on android 2.3.6 using qpython3 using its python console and 
import pip
pip.main(["install","yagmail"])
it seems that the problem is with installation of keyring. 

On android 5.0.1 installing keyring and then yagmail worked after upgrading pip: pip.main(["install","-U", "pip"]), however after restarting console pip stops working, i.e. import pip fails.

QPython3 uses python 3.2.2, and it looks like there is no way to upgrade python version. I realize that the problem might be with QPython3, but I am not sure what anything else is available for python 3 on android.

With respect to yagmail: maybe dependency on keyring should be optional: if it's not installed, do not use it.

**Comment by kootenpv** [comment]
You are totally right that it should be optional. Only on the installation level this is an issue. 

I pushed a new version of yagmail (0.6.159) that does not require keyring. Could you give it a try?

    pip uninstall yagmail
    pip install yagmail

**Comment by dimashi** [comment]
Thank you, Pascal! I will try it tonight.

On Mon, Feb 27, 2017 at 3:17 AM, Pascal van Kooten <notifications@github.com

**Comment by dimashi** [comment]
I tried it, it works. Thank you very much! 
Maybe you should make it an answer to my Q on stackoverflow.

**Comment by kootenpv** [comment]
After it is put on hold it is not possible to answer. But glad it helped.

**Comment by dimashi** [comment]
fixed, thank you!
