### ISSUE TITLE
Yagmail Ignoring Whitespace

### ISSUE THREAD

**Issue by emes4** [kootenpv/yagmail#65]
Hi there,

First of all, yagmail has been a great package to work with.

My goal is to align strings of varied length into three 'columns' in the body of the email. However, I am having an issue with trying to email strings with formatted width such as:

`"{:20s}{:30s}{:20s}\n".format(values1, values2, values3)`

When sent as raw, the whitespace is ignored. I have tried sending it as HTML using `<pre></pre>`, however that adds the given whitespace on top of that string.

Any ideas of how to fix this?

**Comment by kootenpv** [comment]
Maybe try using a HTML `<table>`?

**Comment by emes4** [comment]
Yes that works thank you. Since I am iterating over dictionaries to get the data, I was wondering if there was a 'simpler' solution. However HTML <table> works. Thank you!
