### ISSUE TITLE
Module not working 

### ISSUE THREAD

**Issue by Tomislav12321321313** [kootenpv/yagmail#74]
![2017-06-16-123249_1920x1080_scrot](https://user-images.githubusercontent.com/19170092/27223350-48648d18-5290-11e7-9ef9-cbcc211f4cfa.png)

I installed it and tried to run the script but i always get this issue.

**Comment by kootenpv** [comment]
You probably installed yagmail with a different python version.

You could try:

    python -m pip install yagmail
    python -c "import yagmail; print('No problems')"

**Comment by Tomislav12321321313** [comment]
thanks for fast answer, but i already solved it.
