### ISSUE TITLE
OAuth2 scope has trailing slash that breaks flow

### ISSUE THREAD

**Issue by MrCreosote** [kootenpv/yagmail#78]
```
*snip*
Your 'google_client_id': 
Your 'google_client_secret': 
Navigate to the following URL to auth:
https://accounts.google.com/o/oauth2/auth?client_id=[redacted]&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fgmail.send%2F
```

That results in:
```
400. That’s an error.

Error: invalid_scope

Some requested scopes were invalid. {invalid=[https://www.googleapis.com/auth/gmail.send/]}
```

Removing the `%2F` from the end of the url allows the OAuth flow to continue.

**Comment by kootenpv** [comment]
I accidentally checked in the wrong scope. It is fixed per `yagmail-0.8.172`. Thanks for pointing it out.

Upgrade with `pip install -U --no-cache yagmail`

**Comment by AggressivelyMeows** [comment]
This problem has returned in the latest version. I'm on the 0.11 version but i cant set up oauth.
Same error, same problem

**Comment by kootenpv** [comment]
@AggressivelyMeows Try removing the old file and go through the process again. Oddly, I also had an issue but I just recreated the file and it worked again.

Could you confirm this solves it? I think it was an expiration in my case....
