### ISSUE TITLE
Compatability with other mail-clients

### ISSUE THREAD

**Issue by CorneelDragon** [kootenpv/yagmail#82]
Hi,

Yagmail seems really easy to use / set-up, great! I'm wondering if you plan on making it compatible with other mail-providers as well? Or is it in your opinion already compatible (in that case a readme-section or link to explanation would be much appreciated)?

For instance, when I set the host (with yagmail.SMTP(user ='username', host='host_url') my 'username' still needs to have an @domain-addres otherwise yagmail adds @gmail.com to it. And when I make sure the username on my mail-server is with @domain.com, I get a time-out error (with a task scheduler I am able to send mail via this mail-server so the time-out seems to a problem in my code / yagmail configuration). 

Any pointers?

Bij voorbaat dank! ;)

**Comment by kootenpv** [comment]
Hi,

It does indeed not offer official support for other email providers, though others have been successfully able to send emails with it. I believe mostly the layout could be a problem.

Did you make sure the port is correct for the provider, and not only the host?

Met vriendelijke groet

**Comment by CorneelDragon** [comment]
Hi, 

Problem was on my end 😳  When I was trying to configure it and made several unsuccessful attempts. In response to this my hosting server blocked my IP  (the task scheduler program handles things via a different route so wasn't blocked).  Now it indeed works 👍
