### ISSUE TITLE
sending emails without any authorization

### ISSUE THREAD

**Issue by radoslawoska** [kootenpv/yagmail#99]
Hi, my local mail server does not require any authorization.
It is possible to send the emails via the yagmail _without_ providing user & password?

thank you
Radoslaw

**Comment by kootenpv** [comment]
Yea, have a look at the tests. This is being used there: `SMTP(smtp_skip_login=True, soft_email_validation=False)`

**Comment by radoslawoska** [comment]
Thank you Pascal it works :)
